# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: microsoft/dotnet:onbuild

pipelines:
  default:
    - step:
        script: 
          # https://docs.microsoft.com/ru-ru/dotnet/articles/core/tools/dotnet-restore
          - dotnet restore ClickOnceUtil4/ClickOnceUtil4UI.csproj
          
          # https://docs.microsoft.com/ru-ru/dotnet/articles/core/tools/dotnet-build
          - dotnet msbuild ClickOnceUtil4/ClickOnceUtil4.sln